export const INIT_CHANGE_APPOINTMENT_STATUS = "INIT_CHANGE_APPOINTMENT_STATUS";
export const SET_REQUEST_SUCCESSFUL = "SET_REQUEST_SUCCESSFUL";
export const SET_FALSE_STATE_REQUEST_SUCCESSFUL =
  "SET_FALSE_STATE_REQUEST_SUCCESSFUL";
