export const INIT_USER_DATA = "INIT_USER_DATA";
export const SET_USER_DATA = "SET_USER_DATA";

export const INIT_FETCH_APPOINTMENT_DATA = "INIT_FETCH_APPOINTMENT_DATA";
export const SET_APPOINTMENT_DATA = "SET_FETCH_APPOINTMENT_DATA";

export const INIT_FETCH_UPCOMING_APPOINTMENT_DATA =
  "INIT_FETCH_UPCOMING_APPOINTMENT_DATA";
export const SET_UPCOMING_APPOINTMENT_DATA = "SET_UPCOMING_APPOINTMENT_DATA";
