export const INIT_USER_DATA = "INIT_USER_DATA";
export const SET_USER_DATA = "SET_USER_DATA";

export const INIT_FETCH_APPOINTMENT_DATA = "INIT_FETCH_APPOINTMENT_DATA";
export const SET_APPOINTMENT_DATA = "SET_FETCH_APPOINTMENT_DATA";

export const INIT_FETCH_UPCOMING_APPOINTMENT_DATA =
  "INIT_FETCH_UPCOMING_APPOINTMENT_DATA";
export const SET_UPCOMING_APPOINTMENT_DATA = "SET_UPCOMING_APPOINTMENT_DATA";

export const INIT_CREATE_APPOINTMENT = "INIT_CREATE_APPOINTMENT";
export const SET_CREATE_APPOINTMENT_STATUS = "SET_CREATE_APPOINTMENT_STATUS";
export const SET_FALSE_STATE_CREATE_APPOINTMENT_STATUS =
  "SET_FALSE_STATE_CREATE_APPOINTMENT_STATUS";

export const INIT_UPDATE_APPOINTMENT_DATA = "INIT_UPDATE_APPOINTMENT_DATA";
export const SET_UPDATE_SUCCESS = "SET_UPDATE_SUCCESS"
